# 1. Introduction

## Qu'est-ce que TensorFlow ?

### Présentation de TensorFlow

**TensorFlow** est une bibliothèque open-source développée par Google pour le Machine Learning et le Deep Learning. Lancée en 2015, elle est conçue pour faciliter la création, l'entraînement et le déploiement de modèles d'apprentissage automatique. TensorFlow permet de réaliser des calculs numériques complexes en utilisant des graphes de flux de données, ce qui la rend particulièrement adaptée pour le traitement de grandes quantités de données.

**Pourquoi TensorFlow est-il important ?**

- **Flexibilité** : TensorFlow supporte une variété de modèles, des réseaux de neurones simples aux architectures complexes comme les Convolutional Neural Networks (CNN) et les Recurrent Neural Networks (RNN).
- **Portabilité** : Les modèles TensorFlow peuvent être déployés sur différentes plateformes, y compris les ordinateurs personnels, les serveurs, les appareils mobiles et les navigateurs web.
- **Communauté Active** : En tant que projet open-source soutenu par Google, TensorFlow bénéficie d'une large communauté de développeurs qui contribuent à son amélioration continue.
- **Intégration avec Keras** : TensorFlow intègre Keras, une API haut niveau qui simplifie la construction et l'entraînement de modèles de Deep Learning.

### Applications courantes de TensorFlow dans l'industrie et la recherche

TensorFlow est utilisé dans de nombreux domaines pour résoudre une variété de problèmes complexes :

- **Vision par Ordinateur** : Reconnaissance d'images, détection d'objets, segmentation d'images.
- **Traitement du Langage Naturel (NLP)** : Traduction automatique, analyse de sentiments, génération de texte.
- **Reconnaissance Vocale** : Transcription de la parole en texte, assistants vocaux.
- **Systèmes de Recommandation** : Suggestions personnalisées de produits, films, musique.
- **Séries Temporelles** : Prévisions financières, analyses météorologiques.
- **Recherche Médicale** : Diagnostic assisté par IA, analyse d'images médicales, découverte de médicaments.

**Exemples concrets :**

- **Google Translate** utilise TensorFlow pour améliorer la qualité de ses traductions en utilisant des modèles de Deep Learning.
- **Airbnb** optimise ses résultats de recherche et recommandations en analysant les préférences des utilisateurs avec TensorFlow.
- **Uber** utilise TensorFlow pour prédire la demande de trajets et optimiser les itinéraires.

### Pourquoi apprendre TensorFlow ?

Apprendre TensorFlow vous permettra de :

- **Comprendre les fondements du Deep Learning** et comment construire des modèles performants.
- **Résoudre des problèmes complexes** dans divers domaines en utilisant des techniques avancées d'apprentissage automatique.
- **Améliorer votre employabilité** dans un marché du travail où les compétences en IA et en Deep Learning sont de plus en plus recherchées.

---

**Note :** Dans les sections suivantes, nous allons explorer comment installer TensorFlow, comprendre ses composants de base, et construire notre premier modèle de Deep Learning.

# 2. Installation et Configuration

## Installer TensorFlow

### Installation avec `pip`

La méthode la plus courante pour installer TensorFlow est d'utiliser `pip`, le gestionnaire de paquets pour Python.

#### Prérequis

- **Python +3.10** : Assurez-vous d'avoir une version compatible de Python installée sur votre système.
- **pip** : Généralement installé avec Python. Vous pouvez vérifier sa version avec `pip --version`.

#### Étapes d'installation

1. **Mettre à jour `pip`**

   ```bash
   pip install --upgrade pip
   ```

2. **Installer TensorFlow**

   Pour installer la dernière version stable de TensorFlow :

   ```bash
   pip install tensorflow
   ```

   Si vous disposez d'une carte graphique compatible avec CUDA et que vous souhaitez utiliser l'accélération GPU :

   ```bash
   pip install tensorflow-gpu
   ```

   **Note :** L'installation GPU nécessite des configurations supplémentaires (CUDA Toolkit et cuDNN).


### Vérification de l'installation

Après l'installation, vous pouvez vérifier que TensorFlow est correctement installé en exécutant les commandes suivantes dans un interpréteur Python :

```python
import tensorflow as tf
print(tf.__version__)
```

Si aucune erreur n'apparaît et que la version de TensorFlow s'affiche, l'installation est réussie.

## Configuration de l'environnement

### Utilisation de Google Colab

Pour éviter les problèmes d'installation et commencer rapidement, vous pouvez utiliser **Google Colab**, un service gratuit qui vous permet d'exécuter des notebooks Jupyter dans le cloud.

#### Avantages de Google Colab

- **Pas d'installation nécessaire** : Accès immédiat à un environnement Python avec TensorFlow préinstallé.
- **Accélération GPU gratuite** : Possibilité d'utiliser des GPU pour accélérer l'entraînement des modèles.
- **Partage facile** : Partagez vos notebooks avec d'autres personnes via Google Drive.

#### Comment accéder à Google Colab

1. Rendez-vous sur [Google Colab](https://colab.research.google.com/).
2. Connectez-vous avec votre compte Google.
3. Créez un nouveau notebook en cliquant sur "Nouveau Notebook".

3. **Installer TensorFlow dans l'environnement virtuel**

   ```bash
   pip install --upgrade pip
   pip install tensorflow
   ```

### Notes supplémentaires

- **Gestion des versions** : Assurez-vous que la version de TensorFlow installée est compatible avec votre version de Python.
- **Problèmes courants** : En cas de problèmes lors de l'installation, consultez la [documentation officielle de TensorFlow](https://www.tensorflow.org/install) pour des instructions détaillées.

---

**Conseil :** Si vous débutez, il est fortement recommandé d'utiliser Google Colab pour éviter les complexités liées à l'installation et pour bénéficier de l'accélération GPU sans configuration supplémentaire.

Dans les sections suivantes, nous utiliserons principalement des notebooks Jupyter, que ce soit localement ou via Google Colab, pour écrire et exécuter notre code TensorFlow.

In [ ]:
#installer tensorflow

In [1]:
#vérifier son installation
import tensorflow as tf
print(tf.__version__)

2.18.0


# 3. Premiers Pas avec TensorFlow

## Les Tenseurs

### Comprendre ce qu'est un tenseur

Un **tenseur** est la structure de données fondamentale de TensorFlow. Il s'agit d'une généralisation des vecteurs et des matrices à des dimensions potentiellement supérieures. En termes simples, un tenseur est un tableau multidimensionnel qui contient des éléments de même type.

**Dimensions des tenseurs :**

- **Scalaire (0-D tenseur)** : Un seul nombre.
- **Vecteur (1-D tenseur)** : Une liste de nombres.
- **Matrice (2-D tenseur)** : Une grille de nombres (tableau à deux dimensions).
- **Tenseur de rang N** : Un tableau N-dimensionnel.

![Scalaire_Vecteur_Matrice_Tenseur de rang N](https://miro.medium.com/v2/resize:fit:2000/1*bJfG0fYzsYPOreyztcq6NA.png)

**Pourquoi les tenseurs sont-ils importants ?**

Les tenseurs permettent de représenter des données de différentes formes et dimensions, ce qui est essentiel pour le traitement de données complexes comme les images, les textes ou les séries temporelles en Deep Learning.

### Création et manipulation de tenseurs avec TensorFlow

Commençons par importer TensorFlow :

```python
import tensorflow as tf
```

#### Création de tenseurs

1. **Tenseurs constants :**

   Utilisez `tf.constant` pour créer un tenseur immuable.

   ```python
   # Scalaire
   scalar = tf.constant(3)
   print("Scalaire :", scalar)
   ```

   ```python
   # Vecteur
   vector = tf.constant([1.0, 2.0, 3.0])
   print("Vecteur :", vector)
   ```

   ```python
   # Matrice
   matrix = tf.constant([[1, 2],
                         [3, 4]])
   print("Matrice :", matrix)
   ```

2. **Tenseurs aléatoires :**

   Utilisez `tf.random` pour créer des tenseurs avec des valeurs aléatoires.

   ```python
   random_tensor = tf.random.uniform(shape=(2, 2), minval=0, maxval=1)
   print("Tenseur aléatoire :", random_tensor)
   ```

3. **Tenseurs remplis de zéro ou de un :**

   ```python
   zeros = tf.zeros(shape=(2, 2))
   ones = tf.ones(shape=(3, 3))
   print("Zeros :", zeros)
   print("Ones :", ones)
   ```

#### Propriétés des tenseurs

- **Type de données (`dtype`)** : Type des éléments du tenseur (ex : `tf.float32`, `tf.int32`).
- **Forme (`shape`)** : Dimensions du tenseur.

```python
print("Type de données :", vector.dtype)
print("Forme du vecteur :", vector.shape)
```

#### Manipulation des tenseurs

1. **Indexation et slicing :**

   ```python
   # Accéder au premier élément du vecteur
   first_element = vector[0]
   print("Premier élément :", first_element)

   # Slicing d'une matrice
   sub_matrix = matrix[:, 0]
   print("Première colonne de la matrice :", sub_matrix)
   ```

2. **Changement de forme (reshaping) :**

   ```python
   reshaped = tf.reshape(vector, [3, 1])
   print("Vecteur reshaped :", reshaped)
   ```

3. **Conversion en tableau NumPy :**

   ```python
   numpy_array = vector.numpy()
   print("Tableau NumPy :", numpy_array)
   ```

## Opérations de Base

### Opérations mathématiques simples

TensorFlow fournit une variété d'opérations mathématiques que vous pouvez effectuer sur les tenseurs.

1. **Addition et soustraction :**

   ```python
   a = tf.constant([1, 2, 3])
   b = tf.constant([4, 5, 6])

   addition = tf.add(a, b)
   soustraction = tf.subtract(a, b)

   print("Addition :", addition)
   print("Soustraction :", soustraction)
   ```

2. **Multiplication et division :**

   ```python
   multiplication = tf.multiply(a, b)
   division = tf.divide(b, a)

   print("Multiplication :", multiplication)
   print("Division :", division)
   ```

3. **Opérations mathématiques avancées :**

   ```python
   # Exponentielle
   exp = tf.exp(a)
   print("Exponentielle :", exp)

   # Racine carrée
   sqrt = tf.sqrt(tf.cast(b, tf.float32))
   print("Racine carrée :", sqrt)
   ```

### Utilisation des variables et constantes

#### Constantes

Les constantes sont des valeurs immuables définies à l'aide de `tf.constant`.

```python
const = tf.constant(10)
print("Constante :", const)
```

#### Variables

Les variables sont des tenseurs dont les valeurs peuvent être modifiées après leur création. Elles sont créées avec `tf.Variable` et sont principalement utilisées pour stocker les poids et les biais dans les modèles d'apprentissage.

```python
var = tf.Variable(5)
print("Variable initiale :", var)

# Mise à jour de la variable
var.assign(10)
print("Variable mise à jour :", var)
```

#### Différence entre variables et constantes

- **Constantes (`tf.constant`)** : Immuables après leur création.
- **Variables (`tf.Variable`)** : Muables, leur valeur peut être modifiée.

#### Exemple d'utilisation des variables

Supposons que vous souhaitiez modéliser l'équation linéaire `y = mx + b`, où `m` et `b` sont des variables.

```python
# Initialisation des variables
m = tf.Variable(0.5)
b = tf.Variable(1.0)

# Fonction linéaire
def linear_function(x):
    return m * x + b

# Calcul pour x = 2
x = tf.constant(2.0)
y = linear_function(x)
print("Résultat de y pour x=2 :", y)
```

**Mise à jour des variables :**

Vous pouvez mettre à jour les variables en utilisant les méthodes `assign`, `assign_add`, ou `assign_sub`.

```python
# Augmenter m de 0.1
m.assign_add(0.1)
print("Nouvelle valeur de m :", m)

# Recalculer y avec le nouveau m
y_new = linear_function(x)
print("Nouveau résultat de y pour x=2 :", y_new)
```

---

**Note :** Les variables sont essentielles lors de l'entraînement des modèles, car les algorithmes d'optimisation ajustent les variables (poids) pour minimiser la fonction de perte.

In [3]:
# A vous de jouer
scalar = tf.constant(3)
print("Scalar:", scalar)

Scalar: tf.Tensor(3, shape=(), dtype=int32)


In [4]:
vector = tf.constant([1.0, 2.0, 3.0])
print("Vector:", vector)



Vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [5]:
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])
print(scalar, vector, matrix)


tf.Tensor(5, shape=(), dtype=int32) tf.Tensor([1 2 3], shape=(3,), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
random_tensor = tf.random.uniform(shape=(2, 2), minval=0, maxval=10)
print(random_tensor)


tf.Tensor(
[[5.437356   7.6829576 ]
 [5.0025663  0.46643257]], shape=(2, 2), dtype=float32)


In [8]:
zeros = tf.zeros([3, 3])
ones = tf.ones([3, 3])
print(zeros, ones)


tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [9]:
print("Data type of vector:", vector.dtype)


Data type of vector: <dtype: 'int32'>


In [10]:
print("Shape of matrix:", matrix.shape)


Shape of matrix: (2, 2)


In [12]:
# Access the first element of a vector
first_element = vector[0]
print("First element:", first_element)

# Slice the first column of a matrix
first_column = matrix[:, 0]
print("First column:", first_column)


First element: tf.Tensor(1, shape=(), dtype=int32)
First column: tf.Tensor([1 3], shape=(2,), dtype=int32)


In [13]:
reshaped = tf.reshape(vector, [3, 1])
print("Reshaped vector:", reshaped)


Reshaped vector: tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [14]:
numpy_array = vector.numpy()
print(numpy_array)


[1 2 3]


In [15]:
numpy_array = vector.numpy()
print(numpy_array)


[1 2 3]


In [18]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

add = tf.add(a, b)
subtract = tf.subtract(a, b)
multiply = tf.multiply(a, b)
divide = tf.divide(a, b)

print(add, subtract, multiply, divide)


tf.Tensor([5 7 9], shape=(3,), dtype=int32) tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32) tf.Tensor([ 4 10 18], shape=(3,), dtype=int32) tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [21]:

# Define integer tensor
a = tf.constant([1, 2, 3], dtype=tf.int32)

# Cast to float32 before applying tf.exp
a_float = tf.cast(a, tf.float32)
exp = tf.exp(a_float)

# Output the result
print(exp)


tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)


In [22]:
# Variables for slope (m) and intercept (b)
m = tf.Variable(0.5)  # Slope
b = tf.Variable(1.0)  # Intercept


In [23]:
# Linear function
def linear_function(x):
    return m * x + b


In [24]:
# Input x = 2
x = tf.constant(2.0)
y = linear_function(x)
print("y for x=2:", y)


y for x=2: tf.Tensor(2.0, shape=(), dtype=float32)


In [25]:
m.assign_add(0.1)  # Increase m by 0.1
y_new = linear_function(x)
print("New y for x=2 after updating m:", y_new)


New y for x=2 after updating m: tf.Tensor(2.2, shape=(), dtype=float32)


In [26]:
import tensorflow as tf  # Import the TensorFlow library, which is used for building and training machine learning models.

# Step 1: Create a tensor of integers
# A "tensor" is a data structure used to store values, similar to arrays in other programming languages.
# Here, we are creating a tensor with three integer values: 1, 2, and 3.
# The data type is explicitly set to `int32`, which means each number will be stored as a 32-bit integer.
a = tf.constant([1, 2, 3], dtype=tf.int32)  
print("Step 1: Integer Tensor 'a':", a)  # This shows the tensor and its properties (values, shape, and data type).

# Step 2: Convert the integer tensor to a floating-point tensor
# Many mathematical operations in TensorFlow, such as exponential calculations, only work with floating-point numbers.
# "Casting" means changing the data type of the tensor while keeping the values the same.
# Here, we convert the integer tensor `a` to a floating-point tensor `a_float` with a data type of `float32`.
a_float = tf.cast(a, tf.float32)  
print("Step 2: Float Tensor 'a_float':", a_float)  # Display the new tensor to confirm the conversion.

# Step 3: Calculate the exponential of each element in the floating-point tensor
# The exponential function is a mathematical operation defined as `e^x`, where `e` is approximately 2.718.
# TensorFlow's `tf.exp` function calculates this for each element in the tensor.
# For example, if the tensor contains [1.0, 2.0, 3.0], it computes [e^1, e^2, e^3].
exp = tf.exp(a_float)  
print("Step 3: Exponential Tensor 'exp':", exp)  # The result is a tensor where each value is the exponential of the corresponding value in `a_float`.

# Step 4: Calculate the square root of each element in the floating-point tensor
# The square root of a number is a value that, when multiplied by itself, gives the original number.
# For example, the square root of 4 is 2, because 2 * 2 = 4.
# TensorFlow's `tf.sqrt` function computes the square root for each element in the tensor.
sqrt = tf.sqrt(a_float)  
print("Step 4: Square Root Tensor 'sqrt':", sqrt)  # The result is a tensor where each value is the square root of the corresponding value in `a_float`.

# Summary
# In this code:
# - We started with an integer tensor and converted it to a floating-point tensor.
# - We applied mathematical operations (exponential and square root) to demonstrate how TensorFlow handles tensors.
# - Each step builds on the previous one, showing how to prepare data for computations and apply functions.


Step 1: Integer Tensor 'a': tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Step 2: Float Tensor 'a_float': tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Step 3: Exponential Tensor 'exp': tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)
Step 4: Square Root Tensor 'sqrt': tf.Tensor([1.        1.4142135 1.7320508], shape=(3,), dtype=float32)


### Exercice : Création et Manipulation de Tenseurs avec TensorFlow

Dans cet exercice, vous allez explorer les concepts de base des tenseurs et les manipulations fondamentales en utilisant TensorFlow. L'objectif est de vous familiariser avec la création, les propriétés, et les opérations de base sur les tenseurs.

#### Étapes :

1. **Création de tenseurs :**
   - Créez un **scalaire** de valeur 7.
   - Créez un **vecteur** avec les valeurs `[1.5, 2.5, 3.5]`.
   - Créez une **matrice** 2x2 contenant les nombres `[[1, 2], [3, 4]]`.
   - Créez un **tenseur aléatoire** de taille 3x3 avec des valeurs comprises entre 0 et 5.


In [27]:
# A vous de jouer
import tensorflow as tf  # Import the TensorFlow library.

# Step 1: Creating tensors

# a) Create a scalar (a single number)
# A scalar is a tensor with 0 dimensions (0-D), representing a single value.
scalar = tf.constant(7)  
print("Scalar:", scalar)

# b) Create a vector (a list of numbers)
# A vector is a tensor with 1 dimension (1-D), like a one-dimensional array.
vector = tf.constant([1.5, 2.5, 3.5])  
print("Vector:", vector)

# c) Create a matrix (2-D array)
# A matrix is a two-dimensional tensor, commonly used for linear transformations or grayscale images.
matrix = tf.constant([[1, 2], [3, 4]])  
print("Matrix:", matrix)

# d) Create a random tensor (3x3) with values between 0 and 5
# A random tensor is often used to initialize weights or simulate data.
random_tensor = tf.random.uniform(shape=(3, 3), minval=0, maxval=5)
print("Random Tensor:", random_tensor)


Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Random Tensor: tf.Tensor(
[[2.429523   2.8457685  4.4032125 ]
 [2.8048599  0.9606695  3.044972  ]
 [0.8022964  0.35910785 0.48163176]], shape=(3, 3), dtype=float32)


2. **Propriétés des tenseurs :**
   - Affichez le **type de données** (`dtype`) et la **forme** (`shape`) du vecteur créé à l’étape précédente.

3. **Manipulation de tenseurs :**
   - Utilisez l'**indexation** pour accéder au premier élément du vecteur.
   - Utilisez le **slicing** pour obtenir la première colonne de la matrice.
   - **Reshapez** le vecteur pour obtenir une forme de `(3, 1)`.
   - **Convertissez** le vecteur en tableau NumPy et affichez le résultat.

In [29]:
# A vous de jouer
# Accessing and manipulating tensors

# Step 1: Indexing - Access the first element of the vector
# TensorFlow allows you to use standard Python-style indexing to access elements in a tensor.
first_element = vector[0]
print("First element of the vector:", first_element)

# Step 2: Slicing - Extract the first column of the matrix
# Slicing allows you to select parts of a tensor using ranges. 
# The notation `:` means "select all rows", and `0` selects the first column.
first_column = matrix[:, 0]
print("First column of the matrix:", first_column)

# Step 3: Reshaping - Change the shape of the vector to (3, 1)
# Reshaping changes the structure of the tensor without altering its data.
# Here, we transform the vector into a column tensor with 3 rows and 1 column.
reshaped_vector = tf.reshape(vector, (3, 1))
print("Reshaped vector (3, 1):", reshaped_vector)

# Step 4: Converting to a NumPy array
# TensorFlow tensors can be converted into NumPy arrays using the `.numpy()` method.
# This is useful for integrating TensorFlow with other libraries like NumPy.
numpy_array = vector.numpy()
print("Vector as a NumPy array:", numpy_array)


First element of the vector: tf.Tensor(1.5, shape=(), dtype=float32)
First column of the matrix: tf.Tensor([1 3], shape=(2,), dtype=int32)
Reshaped vector (3, 1): tf.Tensor(
[[1.5]
 [2.5]
 [3.5]], shape=(3, 1), dtype=float32)
Vector as a NumPy array: [1.5 2.5 3.5]


4. **Opérations mathématiques sur les tenseurs :**
   - Créez deux vecteurs `a` et `b` de tailles égales.
   - Effectuez une **addition**, une **soustraction**, une **multiplication**, et une **division** entre les deux vecteurs.
   - Calculez l'**exponentielle** des éléments du vecteur `a` et la **racine carrée** des éléments de `b`.

In [30]:
# A vous de jouer
import tensorflow as tf

# Step 1: Create two vectors of equal size
# We create tensors `a` and `b` with values for demonstration purposes.
a = tf.constant([1.0, 2.0, 3.0])  # A tensor with float32 values
b = tf.constant([4.0, 5.0, 6.0])  # Another tensor with the same shape

# Step 2: Perform basic mathematical operations

# Addition: Adds corresponding elements of the tensors
addition = tf.add(a, b)
print("Addition (a + b):", addition)

# Subtraction: Subtracts elements of `b` from `a`
subtraction = tf.subtract(a, b)
print("Subtraction (a - b):", subtraction)

# Multiplication: Multiplies corresponding elements of the tensors
multiplication = tf.multiply(a, b)
print("Multiplication (a * b):", multiplication)

# Division: Divides elements of `a` by elements of `b`
division = tf.divide(a, b)
print("Division (a / b):", division)

# Step 3: Calculate the exponential of `a`
# The exponential of a number `x` is calculated as e^x, where e is approximately 2.718.
exponential = tf.exp(a)
print("Exponential of a (e^a):", exponential)

# Step 4: Calculate the square root of `b`
# The square root of each element in `b` is calculated using `tf.sqrt`.
square_root = tf.sqrt(b)
print("Square root of b (sqrt(b)):", square_root)


Addition (a + b): tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Subtraction (a - b): tf.Tensor([-3. -3. -3.], shape=(3,), dtype=float32)
Multiplication (a * b): tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
Division (a / b): tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float32)
Exponential of a (e^a): tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)
Square root of b (sqrt(b)): tf.Tensor([2.        2.236068  2.4494898], shape=(3,), dtype=float32)


In [32]:
import tensorflow as tf  # Import TensorFlow library for numerical and tensor operations

# Step 1: Create two vectors (tensors) of equal size
# Tensor `a` contains three float32 values: [1.0, 2.0, 3.0]
# Tensor `b` contains three float32 values: [4.0, 5.0, 6.0]
a = tf.constant([1.0, 2.0, 3.0])
b = tf.constant([4.0, 5.0, 6.0])

# Step 2: Perform basic mathematical operations

# Addition: Adds each element of `a` to the corresponding element in `b`
# Example: [1.0 + 4.0, 2.0 + 5.0, 3.0 + 6.0] = [5.0, 7.0, 9.0]
addition = tf.add(a, b)
print("Addition (a + b):", addition)

# Subtraction: Subtracts each element of `b` from the corresponding element in `a`
# Example: [1.0 - 4.0, 2.0 - 5.0, 3.0 - 6.0] = [-3.0, -3.0, -3.0]
subtraction = tf.subtract(a, b)
print("Subtraction (a - b):", subtraction)

# Multiplication: Multiplies each element of `a` with the corresponding element in `b`
# Example: [1.0 * 4.0, 2.0 * 5.0, 3.0 * 6.0] = [4.0, 10.0, 18.0]
multiplication = tf.multiply(a, b)
print("Multiplication (a * b):", multiplication)

# Division: Divides each element of `a` by the corresponding element in `b`
# Example: [1.0 / 4.0, 2.0 / 5.0, 3.0 / 6.0] = [0.25, 0.4, 0.5]
division = tf.divide(a, b)
print("Division (a / b):", division)

# Step 3: Calculate the exponential of `a`
# Computes the exponential (e^x) for each element in `a`
# Example: e^1.0 ≈ 2.718, e^2.0 ≈ 7.389, e^3.0 ≈ 20.085
exponential = tf.exp(a)
print("Exponential of a (e^a):", exponential)

# Step 4: Calculate the square root of `b`
# Computes the square root (sqrt(x)) for each element in `b`
# Example: sqrt(4.0) = 2.0, sqrt(5.0) ≈ 2.236, sqrt(6.0) ≈ 2.449
square_root = tf.sqrt(b)
print("Square root of b (sqrt(b)):", square_root)


Addition (a + b): tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Subtraction (a - b): tf.Tensor([-3. -3. -3.], shape=(3,), dtype=float32)
Multiplication (a * b): tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
Division (a / b): tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float32)
Exponential of a (e^a): tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)
Square root of b (sqrt(b)): tf.Tensor([2.        2.236068  2.4494898], shape=(3,), dtype=float32)
